name: trip4peru
description: A new Flutter project.


publish_to: 'none' 


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 


flutter:
  uses-material-design: true
  assets:
    - images/
    

 